### ISSUE TITLE
Remove antlr4-annotations module/dependency

### ISSUE THREAD

**Issue by fcurts** [tunnelvisionlabs/antlr4#50]
The POM of `com.tunnelvisionlabs:antlr4-runtime` declares a compile dependency on `com.tunnelvisionlabs:antlr4-annotations`. However, it seems that these annotations have been moved into `antlr4-runtime`, making the `antlr4-annotations` module obsolete.

`org.antlr4` no longer publishes an `antlr4-annotations` module (latest version is 4.3); hence I suspect this is a left-over that should be removed.

**Comment by sharwell** [comment]
The reference release no longer uses the annotations, but this project does. The antlr4-annotations bundle is usable for projects that want the annotations but don't need the rest of ANTLR. Since the classes get embedded in the antlr4-runtime bundle, I was able to mark the dependency as optional so it won't get picked up by downstream projects unless they explicitly depend on it.

**Comment by fcurts** [comment]
Why declare a dependency at all? There is no dependency now that annotations are embedded.

**Comment by sharwell** [comment]
The annotations are embedded by the build process; inside this repository the types are not embedded and omitting the dependency would produce a compilation error.
